### PR TITLE
Add support for ghc 8.8.3 and 8.10.1

### PR DESCRIPTION
**Pull request by erikd**
Also test in travis.

Closes: https://github.com/mitchellwrosen/text-ansi/issues/1

### CODE REVIEW

**Comment by erikd** [comment]
Since this needs a bit of added CPP, this will need a new upload.

**Comment by mitchellwrosen** [comment]
Thanks :)

**Comment by erikd** [comment]
A new release would be great too! :D

**Comment by mitchellwrosen** [comment]
Done!

**Pull request merged**
